### ISSUE TITLE
id should be consistent with to_param for autogenerated pids

### ISSUE THREAD

**Issue by jcoyne** [samvera/active_fedora#457]
This seems odd:

```
p @asset1.to_param
"87/c9/ad/e0/87c9ade0-c84b-4a0b-9458-a83c2f7ac55b"
p @asset1.id
"/87/c9/ad/e0/87c9ade0-c84b-4a0b-9458-a83c2f7ac55b"
```

**Comment by atz** [comment]
@awoods, @ajs6f: can we get an update on this issue?

**Comment by escowles** [comment]
@atz If you mean you would like to have shorter IDs and not have to deal with the PairTree hierarchy, I think the AppleTree module might be useful: https://gitlab.amherst.edu/acdc/acrepo-apple-trees

@awoods I wasn't able to find any docs on how to actually use this, beyond the links from that module's README to some config files.  Would it be possible to add a profile to webapp-plus to make it easy to enable this?

**Comment by awoods** [comment]
@escowles : The apple-trees dependency is available in the current master branch of fcrepo-webapp-plus as of: https://github.com/fcrepo4-exts/fcrepo-webapp-plus/commit/49c8d14747b6db4659e48a4a6046efc21aba3647

Configuration of that component is still required in order to enable its use.

There are caveats related to apple-trees that include the inability to use `COPY` and the fact that existing repository resources would need to be migrated to new paths.

Although this capability shows promise along the lines of this GitHub issue, it would require stakeholder interest and testing to move it forward.
